export default [
  {
    id: 1,
    name: 'News Titre (Portrait)',
    picture: 'example.png',
    width: 300,
    height: 300,
  },
  {
    id: 2,
    name: 'News Titre (Carré)',
    picture: 'example.png',
    width: 300,
    height: 300,
  },
  {
    id: 3,
    name: 'News Textes (Carré)',
    picture: 'example.png',
    width: 300,
    height: 300,
  },
  {
    id: 4,
    name: 'News Textes (Portrait)',
    picture: 'example.png',
    width: 300,
    height: 300,
  },
  {
    id: 5,
    name: 'Article',
    picture: 'example.png',
    width: 300,
    height: 300,
  },
  {
    id: 6,
    name: 'Chronique (Cover)',
    picture: 'example.png',
    width: 300,
    height: 300,
  },
  {
    id: 7,
    name: 'Chronique (Description)',
    picture: 'example.png',
    width: 300,
    height: 300,
  },
  {
    id: 8,
    name: 'Sorties (Projets)',
    picture: 'example.png',
    width: 300,
    height: 300,
  },
  {
    id: 9,
    name: 'Sorties (Singles)',
    picture: 'example.png',
    width: 300,
    height: 300,
  },
  {
    id: 10,
    name: 'Punchline',
    picture: 'example.png',
    width: 300,
    height: 300,
  },
  {
    id: 11,
    name: 'La reco',
    picture: 'example.png',
    width: 300,
    height: 300,
  },
  {
    id: 12,
    name: 'News Titre (Portrait)',
    picture: 'example.png',
    width: 300,
    height: 300,
  },
];
